kind: pipeline
type: docker
name: integration


steps:
    - name: build
      image: mcr.microsoft.com/dotnet/sdk:latest
      commands:
        - dotnet build

    - name: test
      image: mcr.microsoft.com/dotnet/sdk:latest
      enviorment:
        SONAR_TOKEN:
          from_secret: SONAR_TOKEN
      commands:
        - dotnet test
    
    - name: code-analysis
      image: boulundeasv/dotnet-sdk-with-java
      commands:
        - dotnet sonarscanner begin /k:"easv-devops_SonarQubeOldProject_AY32FFaJEVvRW2O60ESB" 
            /d:sonar.host.url="http://sonar.setgo.dk:9000"  
            /d:sonar.token="$SONAR_TOKEN" 
            /d:sonar.cs.vscodecovarage.xml.reportsPaths=covarage.xml /d:sonar.qualitygate.wait=true
        - dotnet build --no-incremental
        - dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
        - dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"
        